name: "Install build dependencies"
description: "Installs build dependencies on GitHub Actions runners"

inputs:
  os:
    description: 'Runner OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Retrieve and install pkg deps based on OS
      if: startsWith(inputs.os, 'ubuntu')
      id: retrieve-pkg-deps
      shell: bash
      run: |
        DEPENDENCIES=$(jq -r --arg os "${{ inputs.os }}" '.[$os] | .[]' $GITHUB_ACTION_PATH/dependencies.json)
        echo $DEPENDENCIES
        sudo apt update
        sudo apt install -y $DEPENDENCIES
    - name: Install Clang-17
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 17
        sudo apt install -y libc++-17-dev libc++abi-17-dev
