name: spdx

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-spdx-headers:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: Apache-2.0
